# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 23:33
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
