# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date', '-id'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['timesheet', '-id']},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='duration',
            field=models.DurationField(blank=True),
        ),
    ]
