# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170522_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
