# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entry_invoiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invoice_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
