# Generated by Django 2.0.1 on 2018-02-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0003_auto_20171001_1018")]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="datetime_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="datetime_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
