# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_invoice_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
