# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170619_1840'),
        ('core', '0006_auto_20170619_0849'),
    ]

    operations = [
    ]
