# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20170620_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='invoiced',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='entries',
            field=models.ManyToManyField(related_name='invoices', to='core.Entry'),
        ),
    ]
