# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 13:09
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def load_initial_data(apps, schema_editor):
    call_command('loaddata', 'initial_data')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170709_0230'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
