# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 13:09
from __future__ import unicode_literals

import django.db.models.deletion

from django.core.management import call_command
from django.db import migrations, models


def load_initial_data(apps, schema_editor):
    call_command('loaddata', 'initial_data')


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=5)),
                ('site', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tenant', to='sites.Site')),
            ],
        ),
        migrations.RunPython(load_initial_data),
    ]
