# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_auto_20170423_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
