# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_auto_20170424_0036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timesheet',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='timesheet',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='task',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='complete',
            new_name='archive',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='complete',
            new_name='archive',
        ),
    ]
