# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_auto_20170426_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['-date', '-id'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['client', '-id']},
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='timesheets.Client'),
        ),
    ]
