# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
        ('timesheets', '0006_project_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='invoicing.Task'),
        ),
    ]
