# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conf',
            options={'verbose_name': 'Configuration', 'verbose_name_plural': 'Configuration'},
        ),
        migrations.RemoveField(
            model_name='conf',
            name='color',
        ),
        migrations.AddField(
            model_name='conf',
            name='smtp_host',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conf',
            name='smtp_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conf',
            name='smtp_port',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conf',
            name='smtp_tls',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='conf',
            name='smtp_user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
