# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conf',
            options={'verbose_name': 'Configuration', 'verbose_name_plural': 'Configuration'},
        ),
        migrations.RemoveField(
            model_name='conf',
            name='color',
        ),
        migrations.AddField(
            model_name='conf',
            name='smtp_host',
            field=models.CharField(default='localhost', max_length=255, verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='conf',
            name='smtp_password',
            field=models.CharField(default='', help_text='This password is stored in plaintext. Use with caution!', max_length=255, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='conf',
            name='smtp_port',
            field=models.PositiveIntegerField(default=25, verbose_name='Port'),
        ),
        migrations.AddField(
            model_name='conf',
            name='smtp_tls',
            field=models.BooleanField(default=False, verbose_name='Use TLS'),
        ),
        migrations.AddField(
            model_name='conf',
            name='smtp_user',
            field=models.CharField(default='', max_length=255, verbose_name='User'),
        ),
    ]
