# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_conf_i18n_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='i18n_language_code',
            field=models.CharField(default='en-us', max_length=5, verbose_name='Language Code'),
        ),
    ]
